### ISSUE TITLE
not working on https

### ISSUE THREAD

**Issue by hassaan-dev** [MidEndProject/node-apprtc#3]
Hi,

Great work. Can you please help me to RUN this on https?

**Comment by fitraditya** [comment]
Hi,
 
You can use HTTPS using nginx.
 
W dniu 2018-07-27 18:27:11 użytkownik hassaan-dev <notifications@github.com> napisał:
Hi,
Great work. Can you please help me to RUN this on https?
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.
 
 
 
--
Fitra Aditya
Certified WebRTC Developer - WSQD
fitra@g.pl - http://fitraditya.com/

**Comment by hassaan-dev** [comment]
Is there any guide line / document available to do it via nginx ? Express server is running this currently, right?

**Comment by fitraditya** [comment]
No, this app using Hapi framework. You can modify index.js to support HTTPS. Check out this solution https://stackoverflow.com/a/34094382.

Or you can also serve HTTPS using nginx by following this post https://www.sitepoint.com/configuring-nginx-ssl-node-js/.

**Comment by hassaan-dev** [comment]
@fitraditya thank you. Let me try first one, if this does not work then I will move to nginx solution.
I will update you after trying this 👍
